name: Sync Docs to /docs for GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'doc/**'
      - '.github/scripts/build-docs.sh'

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Run build-docs script
        run: bash .github/scripts/build-docs.sh

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "🔄 Auto-update GitHub Pages docs"
          git push
